// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
public class practice_problems {
    public static void main(String[] args) {
        int Num1=0;
        int Num2=1;
        int Num3=0;
        int result=0;
        while(Num2<4000000){
            Num3=Num1+Num2;
            if(Num3%2==0){
                result+=Num3;
            }
            Num1=Num2;
            Num2=Num3;
        }
        System.out.println(result);
    }
}
// answer:4613732
